import io
p = 'Brainarr.Plugin/Services/ProviderHealth.cs'
src = io.open(p, 'r', encoding='utf-8').read()

# 1) Add per-provider lock field/helper
old1 = (
"        private readonly ConcurrentDictionary<string, ProviderMetrics> _metrics;\n"
"        private readonly ConcurrentDictionary<string, DateTime> _lastHealthCheck;\n"
"        private readonly Logger _logger;\n"
"        private readonly TimeSpan _healthCheckInterval = TimeSpan.FromMinutes(5);\n"
"\n"
"        public ProviderHealthMonitor(Logger logger)\n"
"        {\n"
"            _logger = logger;\n"
"            _metrics = new ConcurrentDictionary<string, ProviderMetrics>();\n"
"            _lastHealthCheck = new ConcurrentDictionary<string, DateTime>();\n"
"        }"
)
new1 = (
"        private readonly ConcurrentDictionary<string, ProviderMetrics> _metrics;\n"
"        private readonly ConcurrentDictionary<string, DateTime> _lastHealthCheck;\n"
"        // Per-provider locks serialize read-modify-write of ProviderMetrics so that\n"
"        // concurrent Success/Failure callbacks cannot interleave at the moment when\n"
"        // ConsecutiveFailures is being reset.\n"
"        private readonly ConcurrentDictionary<string, object> _providerLocks;\n"
"        private readonly Logger _logger;\n"
"        private readonly TimeSpan _healthCheckInterval = TimeSpan.FromMinutes(5);\n"
"\n"
"        public ProviderHealthMonitor(Logger logger)\n"
"        {\n"
"            _logger = logger;\n"
"            _metrics = new ConcurrentDictionary<string, ProviderMetrics>();\n"
"            _lastHealthCheck = new ConcurrentDictionary<string, DateTime>();\n"
"            _providerLocks = new ConcurrentDictionary<string, object>();\n"
"        }\n"
"\n"
"        private object GetLock(string providerName) =>\n"
"            _providerLocks.GetOrAdd(providerName, _ => new object());"
)
assert old1 in src, 'old1 not found'
src = src.replace(old1, new1)

# 2) RecordSuccess wrap
old2 = (
"        public void RecordSuccess(string providerName, double responseTimeMs)\n"
"        {\n"
"            _metrics.AddOrUpdate(providerName,\n"
"                _ => new ProviderMetrics\n"
"                {\n"
"                    TotalRequests = 1,\n"
"                    SuccessfulRequests = 1,\n"
"                    ConsecutiveFailures = 0,\n"
"                    LastSuccessfulRequest = DateTime.UtcNow,\n"
"                    AverageResponseTimeMs = responseTimeMs\n"
"                },\n"
"                (_, existingMetrics) =>\n"
"                {\n"
"                    var newSuccessfulRequests = existingMetrics.SuccessfulRequests + 1;\n"
"                    var newAverageResponseTime = existingMetrics.AverageResponseTimeMs == 0\n"
"                        ? responseTimeMs\n"
"                        : (existingMetrics.AverageResponseTimeMs * existingMetrics.SuccessfulRequests + responseTimeMs) / newSuccessfulRequests;\n"
"\n"
"                    return existingMetrics with\n"
"                    {\n"
"                        TotalRequests = existingMetrics.TotalRequests + 1,\n"
"                        SuccessfulRequests = newSuccessfulRequests,\n"
"                        ConsecutiveFailures = 0,\n"
"                        LastSuccessfulRequest = DateTime.UtcNow,\n"
"                        AverageResponseTimeMs = newAverageResponseTime\n"
"                    };\n"
"                });\n"
"\n"
"            var updatedMetrics = _metrics[providerName];\n"
"            _logger.Debug($\"{providerName}: Success recorded (Response: {responseTimeMs}ms, Success rate: {updatedMetrics.SuccessRate:F1}%)\");\n"
"        }"
)
new2 = (
"        public void RecordSuccess(string providerName, double responseTimeMs)\n"
"        {\n"
"            ProviderMetrics updatedMetrics;\n"
"            lock (GetLock(providerName))\n"
"            {\n"
"                updatedMetrics = _metrics.AddOrUpdate(providerName,\n"
"                    _ => new ProviderMetrics\n"
"                    {\n"
"                        TotalRequests = 1,\n"
"                        SuccessfulRequests = 1,\n"
"                        ConsecutiveFailures = 0,\n"
"                        LastSuccessfulRequest = DateTime.UtcNow,\n"
"                        AverageResponseTimeMs = responseTimeMs\n"
"                    },\n"
"                    (_, existingMetrics) =>\n"
"                    {\n"
"                        var newSuccessfulRequests = existingMetrics.SuccessfulRequests + 1;\n"
"                        var newAverageResponseTime = existingMetrics.AverageResponseTimeMs == 0\n"
"                            ? responseTimeMs\n"
"                            : (existingMetrics.AverageResponseTimeMs * existingMetrics.SuccessfulRequests + responseTimeMs) / newSuccessfulRequests;\n"
"\n"
"                        return existingMetrics with\n"
"                        {\n"
"                            TotalRequests = existingMetrics.TotalRequests + 1,\n"
"                            SuccessfulRequests = newSuccessfulRequests,\n"
"                            ConsecutiveFailures = 0,\n"
"                            LastSuccessfulRequest = DateTime.UtcNow,\n"
"                            AverageResponseTimeMs = newAverageResponseTime\n"
"                        };\n"
"                    });\n"
"            }\n"
"\n"
"            _logger.Debug($\"{providerName}: Success recorded (Response: {responseTimeMs}ms, Success rate: {updatedMetrics.SuccessRate:F1}%)\");\n"
"        }"
)
assert old2 in src, 'old2 not found'
src = src.replace(old2, new2)

# 3) RecordFailure wrap
old3 = (
"        public void RecordFailure(string providerName, string error)\n"
"        {\n"
"            _metrics.AddOrUpdate(providerName,\n"
"                _ => new ProviderMetrics\n"
"                {\n"
"                    TotalRequests = 1,\n"
"                    FailedRequests = 1,\n"
"                    ConsecutiveFailures = 1,\n"
"                    LastFailedRequest = DateTime.UtcNow,\n"
"                    LastError = error\n"
"                },\n"
"                (_, existingMetrics) => existingMetrics with\n"
"                {\n"
"                    TotalRequests = existingMetrics.TotalRequests + 1,\n"
"                    FailedRequests = existingMetrics.FailedRequests + 1,\n"
"                    ConsecutiveFailures = existingMetrics.ConsecutiveFailures + 1,\n"
"                    LastFailedRequest = DateTime.UtcNow,\n"
"                    LastError = error\n"
"                });\n"
"\n"
"            var updatedMetrics = _metrics[providerName];\n"
"            _logger.Warn($\"{providerName}: Failure recorded (Consecutive: {updatedMetrics.ConsecutiveFailures}, Error: {error})\");\n"
"\n"
"            if (updatedMetrics.ConsecutiveFailures >= 3)\n"
"            {\n"
"                _logger.Error($\"{providerName} has failed {updatedMetrics.ConsecutiveFailures} times consecutively - provider may be unhealthy\");\n"
"            }\n"
"        }"
)
new3 = (
"        public void RecordFailure(string providerName, string error)\n"
"        {\n"
"            ProviderMetrics updatedMetrics;\n"
"            lock (GetLock(providerName))\n"
"            {\n"
"                updatedMetrics = _metrics.AddOrUpdate(providerName,\n"
"                    _ => new ProviderMetrics\n"
"                    {\n"
"                        TotalRequests = 1,\n"
"                        FailedRequests = 1,\n"
"                        ConsecutiveFailures = 1,\n"
"                        LastFailedRequest = DateTime.UtcNow,\n"
"                        LastError = error\n"
"                    },\n"
"                    (_, existingMetrics) => existingMetrics with\n"
"                    {\n"
"                        TotalRequests = existingMetrics.TotalRequests + 1,\n"
"                        FailedRequests = existingMetrics.FailedRequests + 1,\n"
"                        ConsecutiveFailures = existingMetrics.ConsecutiveFailures + 1,\n"
"                        LastFailedRequest = DateTime.UtcNow,\n"
"                        LastError = error\n"
"                    });\n"
"            }\n"
"\n"
"            _logger.Warn($\"{providerName}: Failure recorded (Consecutive: {updatedMetrics.ConsecutiveFailures}, Error: {error})\");\n"
"\n"
"            if (updatedMetrics.ConsecutiveFailures >= 3)\n"
"            {\n"
"                _logger.Error($\"{providerName} has failed {updatedMetrics.ConsecutiveFailures} times consecutively - provider may be unhealthy\");\n"
"            }\n"
"        }"
)
assert old3 in src, 'old3 not found'
src = src.replace(old3, new3)

io.open(p, 'w', encoding='utf-8').write(src)
print('lock count:', src.count('lock (GetLock'))
print('_providerLocks count:', src.count('_providerLocks'))
