default: true

# Allow inline HTML for badges and custom markup in README
MD033: false

# Don’t enforce first-line heading (some wiki pages have intro blocks)
MD041: false

# Line length — documentation often contains URLs / tables
MD013: false

# Fenced code blocks — require language (we annotate by default with `text`)
MD040: true

# Consistent list markers and indentation
MD004: { style: dash }
MD007: { indent: 2 }

# Trailing spaces and blank lines
MD009: { br_spaces: 2, list_item_empty_lines: false }
MD012: { maximum: 1 }

# Headings: no multiple top-level headings, proper spacing
MD022: true
MD025: true
MD026: { punctuation: ".,;:!" }

# Ordered list item prefix — ensure consistent numbering
MD029: true

# Code block surrounds and list separation
MD031: true


MD024: false
