name: Verify Assemblies Manifest
description: Validate MANIFEST.txt for extracted Lidarr assemblies
inputs:
  path:
    description: Path to MANIFEST.txt
    required: false
    default: ext/Lidarr-docker/_output/net6.0/MANIFEST.txt
  strict:
    description: Enforce tag/digest and no tarball fallback
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        MAN="${{ inputs.path }}"
        if [ ! -f "$MAN" ]; then
          echo "Missing MANIFEST.txt at $MAN" >&2
          exit 1
        fi
        echo "=== Assemblies MANIFEST ==="; sed -n '1,120p' "$MAN"

        if [ "${{ inputs.strict }}" = "true" ]; then
          # No tarball fallback allowed in strict mode
          if grep -q '^Fallback:\s*tarball' "$MAN"; then
            echo "Assemblies came from tarball fallback; expected Docker (plugins branch)." >&2
            exit 1
          fi
          EXPECT_TAG="ghcr.io/hotio/lidarr:${LIDARR_DOCKER_VERSION:-}"
          EXPECT_DIG="${LIDARR_DOCKER_DIGEST:-}"
          if [ -n "$EXPECT_DIG" ]; then
            grep -q "^DockerDigestEnv: ${EXPECT_DIG}\b" "$MAN" || { echo "Manifest digest mismatch: expected ${EXPECT_DIG}" >&2; exit 1; }
          else
            grep -q "^DockerTag: ${EXPECT_TAG}\b" "$MAN" || { echo "Manifest tag mismatch: expected ${EXPECT_TAG}" >&2; exit 1; }
          fi
        else
          echo "Non-strict mode: skipping tag/digest enforcement"
        fi
