name: 🐛 Bug Report
description: Report a bug or issue with Brainarr
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! 🙏
        
        Before submitting, please:
        - ✅ Check the [FAQ](https://github.com/yourusername/brainarr/blob/main/FAQ.md)
        - ✅ Check the [Troubleshooting Guide](https://github.com/yourusername/brainarr/blob/main/TROUBLESHOOTING.md)
        - ✅ Search existing issues to avoid duplicates

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you've completed these steps
      options:
        - label: I have read the FAQ and troubleshooting guide
          required: true
        - label: I have searched for existing issues
          required: true
        - label: I have included all required information below
          required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Category
      description: What type of issue are you experiencing?
      options:
        - Installation/Setup
        - Provider Connection
        - Recommendations Not Generated
        - Poor Quality Recommendations
        - Performance Issues
        - Configuration/Settings
        - Error Messages
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly describe what the bug is and what you expected to happen
      placeholder: |
        **What happened:**
        A clear description of what the bug is.
        
        **What you expected:**
        A clear description of what you expected to happen.
        
        **Steps to reproduce:**
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true

  - type: input
    id: brainarr-version
    attributes:
      label: Brainarr Version
      description: Which version of Brainarr are you using?
      placeholder: "1.0.0"
    validations:
      required: true

  - type: input
    id: lidarr-version
    attributes:
      label: Lidarr Version
      description: Which version of Lidarr are you using?
      placeholder: "4.0.0.0"
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider are you using?
      options:
        - Ollama (Local)
        - LM Studio (Local)
        - OpenAI (Cloud)
        - Anthropic (Cloud)
        - Google Gemini (Cloud)
        - Perplexity (Cloud)
        - Groq (Cloud)
        - DeepSeek (Cloud)
        - OpenRouter (Cloud)
        - Multiple providers
        - Not applicable
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: What platform are you running on?
      options:
        - Windows
        - Linux
        - macOS
        - Docker
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Files
      description: |
        Please provide relevant log entries from Lidarr
        **IMPORTANT: Remove any API keys or sensitive information!**
      placeholder: |
        Paste log entries here...
    validations:
      required: false