name: 🐛 Bug Report
description: Report a bug in Brainarr
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the sections below to help us fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: dropdown
    id: provider
    attributes:
      label: AI Provider
      description: Which AI provider were you using when the bug occurred?
      options:
        - Ollama (Local)
        - LM Studio (Local)
        - OpenAI
        - Anthropic (Claude)
        - Perplexity
        - OpenRouter
        - DeepSeek
        - Google Gemini
        - Groq
        - Not applicable
        - Other (specify in description)
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please include relevant Lidarr logs (Settings > General > Logging)
      placeholder: |
        Paste logs here... (remove any API keys or sensitive information)
      render: text

  - type: input
    id: lidarr-version
    attributes:
      label: Lidarr Version
      description: What version of Lidarr are you running?
      placeholder: "e.g., 2.0.7.4136"
    validations:
      required: true

  - type: input
    id: brainarr-version
    attributes:
      label: Brainarr Version
      description: What version of Brainarr are you using?
      placeholder: "e.g., v1.0.0"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - Linux (Ubuntu/Debian)
        - Linux (CentOS/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - macOS
        - Docker
        - Unraid
        - Synology
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration details, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this hasn't been reported
          required: true
        - label: I have removed any sensitive information (API keys, personal data) from logs
          required: true
        - label: I am using a supported version of Lidarr (v1.0+)
          required: true