name: 📚 Documentation Request
description: Request documentation updates, fixes, or new guides
title: "[Docs] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Help us keep docs clear and useful. Describe what needs to change.

  - type: input
    id: topic
    attributes:
      label: Topic / Area
      description: What part of the project does this concern?
      placeholder: e.g., CI setup, local dev, provider config
    validations:
      required: true

  - type: textarea
    id: change
    attributes:
      label: Requested Change
      description: What should be added/updated/removed?
      placeholder: Be as specific as possible
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Pages / Files
      description: List the docs or paths to update
      placeholder: |
        - BUILD.md
        - DEVELOPMENT.md
        - docs/PROVIDER_SUPPORT_MATRIX.md

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add screenshots, examples, or related links
