name: 🤖 AI Provider Request
description: Request support for a new AI provider
title: "[Provider] Add support for "
labels: ["provider-request", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new AI provider! This helps us prioritize which providers to add next.

  - type: input
    id: provider-name
    attributes:
      label: Provider Name
      description: What is the name of the AI provider?
      placeholder: "e.g., Cohere, Hugging Face, Azure OpenAI"
    validations:
      required: true

  - type: input
    id: provider-url
    attributes:
      label: Provider Website
      description: What is the official website or documentation URL?
      placeholder: "e.g., https://cohere.ai/"
    validations:
      required: true

  - type: dropdown
    id: provider-type
    attributes:
      label: Provider Type
      description: Is this a local or cloud-based provider?
      options:
        - Local (runs on my computer)
        - Cloud (API service)
        - Both (supports local and cloud)
    validations:
      required: true

  - type: dropdown
    id: api-type
    attributes:
      label: API Type
      description: What type of API does the provider use?
      options:
        - REST API (HTTP/JSON)
        - OpenAI-compatible API
        - GraphQL
        - gRPC
        - WebSocket
        - Custom protocol
        - No API (local binary)
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: why-useful
    attributes:
      label: Why is this provider useful?
      description: What makes this provider special or different from existing ones?
      placeholder: |
        - Better music knowledge
        - Cheaper pricing
        - Privacy features
        - Specialized capabilities
        - etc.
    validations:
      required: true

  - type: textarea
    id: pricing
    attributes:
      label: Pricing Information
      description: What are the costs for using this provider?
      placeholder: |
        - Free tier: ...
        - Paid plans: ...
        - Per-token pricing: ...
        - Or: Completely free / Open source

  - type: input
    id: documentation
    attributes:
      label: API Documentation
      description: Link to API documentation (if available)
      placeholder: "https://..."

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical information that would help with implementation
      placeholder: |
        - Authentication method (API key, OAuth, etc.)
        - Request/response format
        - Rate limits
        - Special requirements
        - etc.

  - type: dropdown
    id: priority
    attributes:
      label: Community Interest
      description: How much community interest do you think there would be?
      options:
        - High - Many people would use this
        - Medium - Some people would find it useful
        - Low - Niche use case
        - Unknown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that would be helpful
      placeholder: Examples, comparisons to existing providers, etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have checked that this provider isn't already supported
          required: true
        - label: I have checked existing provider requests to avoid duplicates
          required: true
        - label: This provider has a publicly available API or is open source
          required: true