using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly
[assembly: AssemblyTitle("Brainarr.Plugin")]
[assembly: AssemblyDescription("AI-powered music recommendation plugin for Lidarr")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("RicherTunes")]
[assembly: AssemblyProduct("Brainarr")]
[assembly: AssemblyCopyright("Copyright © RicherTunes 2025")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("A4C7B8AA-7F67-4C38-9A5E-7CA4E2C5D827")]

// AssemblyVersion and AssemblyFileVersion are intentionally NOT declared here.
// They are generated by the SDK from Directory.Build.props (which reads the
// top-level VERSION file). Hardcoding them here would silently rot — the
// previous "1.3.2.0" literal stayed put through 1.4.0 and 1.4.1 releases,
// causing /api/v1/system/plugins to report stale installedVersion.
// AssemblyInformationalVersion is also SDK-generated and tracks Directory.Build.props.

// Mark as Lidarr plugin
[assembly: AssemblyMetadata("PluginType", "ImportList")]
[assembly: AssemblyMetadata("PluginName", "Brainarr")]
